# Generated by Django 5.1.2 on 2024-10-17 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='rubros',
            new_name='pedido',
        ),
    ]
