# Generated by Django 5.1.2 on 2024-10-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Restaurante', '0002_rename_rubros_cliente_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
    ]
